### ISSUE TITLE
Save Edit bibliography data

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#10]
DEPiCTed saves the bib data automatically HOWEVER, just the upper fields. It saves all entered entries, despite source type and Contributor. [well I did not enter information for all fields] The information I entered in these two fields was unfortunately not saved when changing to the Editor and returning again. 

This was the reason I typed in the information again and manually clicked on SAVE. Unfortunately I was told that my data could not be saved as: 'DepictEd' object has no attribute 'bib_coords_str'. But I thought that this Error message has maybe something to do with the problems I have when importing a file. 

This is why I started from scratch, meaning, I imported a txt file [though the text does not appear in the editor]. This time I started by typing in the bibliographical data information. However, I recognised that even if I click on Save all, only the upper field information will be saved. The Contributor, as well as the Source Type had to be "re-entered" but were never saved, neither automatically, nor by clicking on Save all.

**Comment by magnusnissel** [comment]
Issues #11  and #9 are probably related to this one. The software still looks for fields that no longer exist (and shouldn't have => coordinates for bib entries). Should be easy to fix.
