### ISSUE TITLE
Convert newlines to white space and Convert single newlines to white space

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#12]
We think we know why you added the options “Convert newlines to white space” and “Convert single newlines to white space”. If we are not mistaken it should facilitate the glossing later on. However, we discovered some issues here: 
1. First of all, according to us, there should not be two options but just a single one saying: 
“Convert newline(s) to white space”, which will be sufficient
2. I guess it is necessary for the glossing to convert newlines to white spaces, so would it be possible to have it automatically done? You did it in the same way for the replace ampersands and replace angle brackets option. It would be perfect if it works with the newlines as well so that newlines are converted to whitespaces when contributors import a txt file into the editor
3. We recognised that the button works with excerpts. However, as soon as we have a full text the tool crashes.

**Comment by magnusnissel** [comment]
Here is my rationale for having both (which leads to the reason why I haven't automated this):

In some documents multiple newlines may be used to structure the text into paragraphs. In this case the "Convert single newlines to white space" will cause something like

"This is a contrived
  text example"

to be converted to "This is a contrived text example" while a document that looks like

"This is another contrived
  text example. But in this case there are multiple paragraphs.

  This is another paragraph that is separated by two linebreaks. It continues..."

will be changed to
 " This is another contrived text example. But in this case there are multiple paragraphs.
   This is another paragraph that is separated by two linebreaks. It continues..."

Retaining the line break between the two "paragraphs". If there only were a "replace any number of newlines with a single whitespace" this would turn into:

 " This is another contrived text example. But in this case there are multiple paragraphs.  This is      another paragraph that is separated by two linebreaks. It continues..."

For most documents, this will be fine, but in the case that you want to keep "2+ linebreaks" as a useful visual clue it is neat to have the "single only" option in my opinion. However, I can easily remove that one.

This is also why no automation is currently implemented. Having the "convert any number of newlines to a whitespace" automatically applied will cause the whole document to not have any visual newlines which (in my opinion) makes it a lot more cumbersome to find and tag excerpts in the text. If this is what you want, I can however easily add this as well.


By the way, If I am not mistaken, if you select a text passage and click on "gloss" it should automatically replace all the newlines with a whitespace in the selected to-be-glossed passage.


3: Just for the protocol: This should be a separate issue  and please include the error message provided by the tool as it crashes (if possible, it should appear in the black console window) and/or the name of a file I can test this with.

**Comment by DamarisNeuhof** [comment]
I will discuss this with Viveka first and then get back to you again. 
I think if it is really the case that if one selects a text passage and clicks on "gloss" that it automatically replaces all the newlines with a whitespace, then it would make more sense that it is NOT automatically done to the whole text when importing it into DEPiCTed.  Because, yes, you are right that the text will look more cumbersome if all newlines are replaced. So in my opinion it should then probably not automatically be done when importing files. However, I have to wait and see what Viveka thinks about it.
