### ISSUE TITLE
Not really an issue but rather a question concerning the logfile

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#13]
The other issue, or well, it is rather a question which came up has to do with the logfile:
I think previously it was that the log file was saved per file/document. Now it seems that there is one logfile independent of the file one is working with and that there are only displayed the “happenings” of the day. It might be that I am mistaken here, or that this is the way it should be…. – It was just something we weren't sure about.

**Comment by magnusnissel** [comment]
This sounds like a bug. The idea is to have a log file for each document. Thanks for reporting, I will take a look at it.
