### ISSUE TITLE
Crashes when replacing newlines with whitespace

### ISSUE THREAD

**Issue by magnusnissel** [magnusnissel/DEPiCTed#14]
"We recognized that the [replace newlines] button works with excerpts. However, as soon as we have a full text the tool crashes." (from #12)

@DamarisNeuhof  Please provide me with (the name of a) sample file where this occurs.

**Comment by DamarisNeuhof** [comment]
I just send you an email with a full text (Matches). 
Unfortunately, the black box does not show any error message, neither does one occur in DEPiCTed. It just says "Keine Rückmeldung" and not matter how long I wait, it won't disappear.

**Comment by magnusnissel** [comment]
Okay, this issue is only "sort of" fixed. The "crash" (or slowdown, depending on machine) was caused by the word-wrapping function of tk.text being overwhelmed with very long lines. In longer test files, the
whole documents ended up on a few long lines (or even just a single one). Now the mean line length (in characters) after replacement is calculated and if it exceeds a threshold (currently 800 chars/line) then the the conversion will be reset and only every second newline will be replaced. It is still possible to get down to fewer (or none) newlines by simply calling the function multiple times, if desired.

Note: There would still be issues if there are very long lines as outliers since then the mean may still be below the threshold. It may make sense to eventually trigger the adjutsment not an mean length but on depending on the length of the longest line.
