### ISSUE TITLE
Tagging in footnotes

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#17]
One is not able to tag something as situation, attitude, setting, description in a footnote which however should be possible. It worked well in the previous version.

**Comment by DamarisNeuhof** [comment]
This is rather strange. It does not work in the exe file, but if you download the zip folder from git gub it works.

**Comment by magnusnissel** [comment]
Not a bug, but a case of the wrong DTD file being bundled with the zip file.
