### ISSUE TITLE
Logfile

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#18]
Actually, the logfile works as it should but I nonetheless want to report one thing which we happened to recognize by conincidence. 
If you start DEPiCTed and go directly to "View logfile" (without having imported any text etc) the logfile already has an entry saying: Could not open the text file. Please save it as unicode (UTF-8) first. (2016-07-28T09:18:20)
I do not think that contributors go to the logfile first without having imported a .txt file... but I wanted to report it nonetheless.

**Comment by magnusnissel** [comment]
Good point, this needs exception handling to hide that message.
