### ISSUE TITLE
Issue gestrichelte Linie

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#19]
Ich weiß leider nicht genau, wie ich dieses Issue bezeichnen soll, aber in der neuen Version ist es so, dass wenn ich auf File, Edit, Find oder Help gehe ganz oben eine gestrichelte Linie zu sehen ist. Ich kann auch auf diese drauf klicken und dann öffnet sich zum Beispiel das File Menu in einem separaten Fenster, bzw das Edit Menue etc. Dies sollte nicht möglich sein.

**Comment by DamarisNeuhof** [comment]
Wir haben das Testen nun erstmal gestoppt. Sobald du das Issue hier auf Git Hub als gelöst markierst, werden Jasmin und ich erneut Testen... Aber wir denken es macht mehr Sinn zu warten, bis dieses Problem gelöst ist.

**Comment by magnusnissel** [comment]
Es handelt sich bei der Linie um ein sogenanntes "tear-off menu", damit der Nutzer dies (bei Bedarf) frei platzieren kann um gewisse Befehle leicht erreichbar zu haben. Ich kann es aber auch schnell wieder entfernen, wenn ihr meint es sorgt eher für Verwirrung / ist nicht nützlich.

Ich verstehe aber ehrlichgesagt nicht ganz, warum diese Issue das weitere Testen verhindert. Übresehe ich da etwas?

**Comment by magnusnissel** [comment]
Hallo Damaris,

das hatte ich eigentlich als neues Feature eingebaut, bitte also nicht das
testen stoppen. Ich kann es aber wieder herausnehmen. Ich dachte es wäre
praktisch, wenn man sich häufig verwendete Menüpunkte frei auf dem
Bildschirm plazieren könnte.

Viele Grüße

Magnus

PS: Ich glaube es ist nie eine gute Idee das Testen zu stoppen wegen 1-2
Issues, sofern die das Testen nicht unmöglich machen

**Comment by DamarisNeuhof** [comment]
Sorry nochmal für die Verwirrung. Wir dachten wie gesagt zunächst, dass es ein größerer Fehler sei... und dass dann Auswirkungen auf alles gehabt hätte. Sind fleißig am Testen :-) Bis jetzt sieht es gut aus

**Comment by magnusnissel** [comment]
Ich hätte es wirklich im Update erwähnen sollen ;)
