### ISSUE TITLE
Help Button vs View Manual

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#20]
Hierbei handelt es sich nicht um ein wirkliches Issue.
Jasmin und ich haben heute morgen gesehen, dass du einen Help Button neu in das Tool eingebaut hast. Dieser gefällt uns sehr sehr gut, da Nutzer wenn sie Hilfe brauchen eher über einen Help Button Hilfe suchen als über einen Tab View Manual.

Eine Frage ist nur, ob nicht der View Manual Tab somit überflüssig wird. Was ist denn deine Meinung dazu? Ich glaube als Nutzer würde ich eher über den Help Button gehen und ich persönlich finde das man nicht beides benötigt. 
Viveka ist ja im Moment  nicht da... und ich weiß nicht wie es ihr lieber ist. 

Leider wird sich das Manual nun noch etwas weiter verzögern, da ich nun alle Videos nochmal neu machen muss, da ja das Help neu dazu gekommen ist und somit die Screenshots und Videos die ich letzte Woche gemacht habe wieder nicht mehr mit dem Bild übereinstimmen, was die Beitragenden erhalten werden. Ich schlage vor, dass wir gemeinsam überlegen, ob wir das View Manual drin lassen oder erst mal rausnehmen für die Glossless Version (wie gesagt, meine Tendenz geht zum rausnehmen, da wir ja den Help Button haben). Wenn wir dann die Version haben wie sie sein soll gibst du mir dein "GO", damit ich die Videos neu machen kann... und sie dann auch erst mal so bleiben können, selbst falls es noch kleine Korrekturen am Tool gibt.

**Comment by magnusnissel** [comment]
Ja, ich denke auch das, dies ausreichen sollte (ausserdem sollte ein Druck auf F1 nun in den meisten Kontexten auch das Dokument direkt öffnen), wollte es aber noch nicht entfernen, da es mMn eine größere Veränderungen als z.B. die tear-off menus wäre ;). 

Ich kann alternative auch das Help wieder entfernen, dann musst du die Videos nicht neu machen. Bzw, wäre es dramatisch wenn das Help auf den Videos, die es eh nicht behandeln, fehlt?
