### ISSUE TITLE
Problem replace angle brackets

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#21]
Well, we once had a similar problem, but here is something new. 
As you said, we actually do have a provision in place to make sure that angle brackets that are part of DEPiCTed tags remain and don't get escaped when clicking on replace angle brackets. This seems to work for those excerpts where there is a page number and for those where there is none. However if you have a page number such as Roman numerals then it does not work. During the testing we recognised that if there is a Roman numeral (because the Preface pages had Roman numerals) then the Replace angle brackets will also delete the first bracket of the excerpt tag.

**Comment by magnusnissel** [comment]
Right, I think right now the regex only anticipates arabic, will change this to allow basically anything to be put as a page number including strings like "preface" for the purpose of checking during replacement.

**Comment by DamarisNeuhof** [comment]
This works now!
