### ISSUE TITLE
Delete non-DEPiCT tags

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#22]
If I am not mistaken this is one of the things which is automatically "applied" to the data when a file is imported into the editor. However, I recognised that if I import a file with non DEPiCT tags into the editor, than the non-DEPiCT tags are actually not deleted but rather replaced. I was just unsure if this is wanted...or if they should rather really be deleted... because otherwise they will still appear in the text - just without angle brackets...

**Comment by DamarisNeuhof** [comment]
By the way, if I am in the Text Edit Mode and I create a non-DEPiCT tag, I normally get an error message. If I click Delete non-DEPiCT tag then the tag will really be deleted. 

However, in the upper case, I could add non-DEPiCT tag and DEPiCTed does not even give me an error message. So I added <zum></zum> and did not receive an error message

**Comment by DamarisNeuhof** [comment]
Just a thing I am curious about: I recognised that I am able in the Edit Mode to add tag pairs such as, for instance, <zum> </zum>, or <opa> </opa> etc. I mean, contributors are told that there is a predefined set of tags but generally, it is possible to add additional tag pairs... - is this wanted or maybe this isn't doing any harm as DEPiCTed does not recognise them as tags...

**Comment by magnusnissel** [comment]
This is not automatically applied, though I could change that. Not sure if there are any potential downsides, though. I think it may be wise to keep it manual so that a user can first leverage some of the tag information (e.g. <p> paragraph tags) before removing them.

I will move the other two points into separate issues
