### ISSUE TITLE
Freedom in text edit mode

### ISSUE THREAD

**Issue by magnusnissel** [magnusnissel/DEPiCTed#25]
@DamarisNeuhof:
> Just a thing I am curious about: I recognised that I am able in the Edit Mode to add tag pairs. I mean, contributors are told that there is a predefined set of tags but generally, it is possible to add additional tag pairs... - is this wanted or maybe this isn't doing any harm as DEPiCTed does not recognise them as tags...

**Comment by magnusnissel** [comment]
In Text Edit Mode the user can do all kind of things to cause themselves problems. That's why the mode should only be used when absolutely necessary. It would be rather difficult to protect the user from doing stupid things here without removing the reason this mode exists, e.g. to allow careful & savvy users to do stuff that goes beyond the scope of what DEPiCTed does or fix text problems that weren't noticed in advance.

**Comment by DamarisNeuhof** [comment]
Okay... so we simply have to hope that the users are only using our tags. Plus, they are told that they are only allowed to use our tags....

**Comment by magnusnissel** [comment]
If they use other tags, they will get XML error messages. If they add DEPiCTed tags using Text Edit Mode instead of the buttons than in many cases it will make no difference, and in other cases it will cause them all kind of problems. But we are telling them not to do that and use the buttons anyway. Fortunately we are dealing with adult academics, right?
