### ISSUE TITLE
Excerpt <ex p="preface">﻿ cannot be deleted via Remove tag

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#27]
I just tried to create an excerpt in which instead of a page number I wrote preface. I cannot delete this one. (Even though, I have to say, I do not think that someone would really write preface as most of the time a preface has a certain kind of numbers) -> Just wanted to report it

**Comment by magnusnissel** [comment]
Ah, the consequences of changing only one part of the code. I'll fix this in a minute.
