### ISSUE TITLE
Missing Export Folder

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#28]
Matthias is back in the office and he wanted to start testing as well. So he downloaded the DEPiCTed zip.... but since today the export folder is missing again. On Friday it was still there...

**Comment by DamarisNeuhof** [comment]
This was an error sorry...

**Comment by DamarisNeuhof** [comment]
This was an error. The export folder appears as soon as one opens DEPiCTed for the first time. Sorry for that...

**Comment by magnusnissel** [comment]
No worries ;)
