### ISSUE TITLE
Missing Export Folder

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#3]
In der derzeitigen Version gibt es im DEPiCTed keinen Export Ordner mehr. Der Button File > Export project existiert zwar, aber man erhält eine Fehlermeldung wenn man versucht einen Export durchzuführen, was vermutlich daran liegt, dass auch der entsprechende Ordner nicht mehr existiert.

**Comment by magnusnissel** [comment]
Resolved.
