### ISSUE TITLE
Too cluttered source type portrayal

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#5]
Die Source type Liste wird nun auch problemlos unter View manual angezeigt.
Allerdings ist die Art und Weise der Darstellung etwas problematisch, da der Beitragende scrollen muss um die Definition lesen zu können. Vielleicht kannst du vorerst die Beispiele rausnehmen, damit man die komplette Definition sieht und nicht scrollen muss. Für eine spätere Version wäre es allerdings wichtig, dass alle drei Spalten vorhanden sind, dann allerdings von der Darstellungsart her mehr wie in einer Tabelle, sodass man quasi einfach einen Zeilenumbruch hat, anstatt scrollen zu müssen.

**Comment by magnusnissel** [comment]
Agreed. Not sure yet if this is easy to fix with the available UI elements, but I will remove the examples for now and we'll discuss a new layout for the help page soon. 

As documentation gets more detailed it may actually make sense to move the help setting to external files (HTML or PDF) that can then be opened with a click from the tool. This would also make it easy to embed screenshots or graphics. Thoughts? @DamarisNeuhof

**Comment by DamarisNeuhof** [comment]
I talked to Viveka about that issue and we came to the conclusion that your idea of opening the help manual in a new window sounds fine to us. You are totally right that it allows a more straightforward updating of help documents.
