### ISSUE TITLE
Annotating in footnotes

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#6]
-	Sprachbeispiele lassen sich auch in Fußnoten als solche problemlos taggen.
-	Es ist im Moment aber nicht möglich, andere Tags in der Fußnote zu setzen. Es sollte auch möglich sein, Text in der Fußnote als Situation, Setting, Attitude und Description zu annotieren.

**Comment by magnusnissel** [comment]
Resolved. The rules for elements inside the document text are specified in depicted_text.dtd file inside the resources folder. DTDs can easily be adjusted (in any text editor) without programming knowledge. See http://www.w3schools.com/xml/xml_dtd_intro.asp for a brief introduction.

In this case the line

<!ELEMENT fn (#PCDATA|com|b|i|sup|sub|pb|lb|d)*>

was changed to

<!ELEMENT fn (#PCDATA|com|b|i|sup|sub|pb|lb|d|sit|set|att|lng)*>
