### ISSUE TITLE
Replace angle brackets Issue

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#7]
Ein neues Problem welches mir aufgefallen ist, betrifft die Möglichkeit Replace angle brackets. 
Folgendes ist die Problematik: Ich habe einen Volltext, in dem ich die Exzerpte von jemandem annotiere. Da die Person, die exzerpiert hat, auch Kommentare ergänzt hat, muss ich diese im Text Edit Mode an die passenden Stellen kopieren. Allerdings hat die Person eckige Klammern [=angle brackets] verwendet. Nun erhalte ich eine Fehlermeldung wenn ich die Daten speichern will, also klicke ich auf Edit> Replace angle brackets. Aber anstatt dass nur jene Klammern ersetzt werden, die problematisch sind, wird auch immer das öffnende Exzerpt Tag Element ersetzt, wie z.B.: &lt;ex p="18"&gt. Dann kann man wieder nicht mehr speichern, da logischerweise dann open und end tag nicht mehr passen. Also müssen erst alle Exzerpt Tags manuell gelöscht werden, damit überhaupt gespeichert werden kann.

**Comment by magnusnissel** [comment]
Resolved. There was already a provision in place to make sure that angle brackets that are part of DEPiCTed tags remain that way and don't get escaped. However, the RegEx didn't anticipate the "p" attribute of ext. Changed to accept a single arbitrary attribute with a numerical value (e.g. p="18").
