### ISSUE TITLE
Remove data tags

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#8]
-	Du sagtest ja, dass sich Dokumente, die wir mit der Glossed Version bearbeitet haben, eigentlich problemlos funktionieren sollten. Jetzt habe ich den folgenden Fall. Ich habe eine alte Datei von mir genommen, in der ich Data tags habe und die ich auch bereits geglossed hatte. Will ich hier nun einen Data tag löschen ist dies nicht möglich und ich erhalte die Fehlermeldung: „Data tags containing glosses may not be removed“  Für externe Beitragende ist es auch auf keinen Fall schlimm, denn dadurch dass sie ihre Daten noch nicht geglossed haben, sollte diese Fehlermeldung nicht erscheinen. 
Ich verstehe auch warum die Fehlermeldung bei uns erscheint… bedeutet das aber, dass ich im Moment nicht in der Lage bin, Data tags zu löschen?

**Comment by magnusnissel** [comment]
This is, as we discussed, working as intended. New contributors won't have glossed data and you are able to deal with this a)  by switching to the gloss-supporting WIP version using the INI or b) removing the gloss/data tags carefully by hand in Text Edit Mode. Though I don't know why the latter option would be chosen.
