### ISSUE TITLE
Problem Importing txt. Files

### ISSUE THREAD

**Issue by DamarisNeuhof** [magnusnissel/DEPiCTed#9]
Unfortunately I have a problem importing a txt file in the new version. I proceed as I always did but the text of the imported txt file won't appear in the Editor. In the header of DEPiCTed the txt-file-name appears but the text is not there. 
Instead the cursor is visible in the Editor window and I can simply add text even though I am not in the text edit mode. 
I am unsure whether this is an issue only happening to me, but I will ask Matthias asap and inform you.

**Comment by magnusnissel** [comment]
See issue #10
